M48
; DRILL file {KiCad 8.0.2} date 2024-12-14T16:16:44+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-14T16:16:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X200.0Y-34.0
X221.0Y-34.0
X241.0Y-34.0
T2
X165.55Y-236.43
X254.45Y-236.43
T3
X180.0Y-90.0
X180.0Y-220.0
X240.0Y-90.0
X240.0Y-220.0
M30
